#!/bin/sh
#
# Load French Azerty keymap...
#

case "$1" in
  start)
    loadkmap < /etc/fr-pc.kmap
    ;;
    
  stop)
    ;;
    
  restart|reload)
    "$0" stop
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

