#!/bin/sh
#
# Start Wifi AP...
#

case "$1" in
  start)
    if [ -d /sys/class/net/wlan0 ]; then
        if [ -x $(command -v hostapd) ]; then
            echo "Run Wifi AP..."
            hostapd -B /etc/hostapd.conf
            [ $? = 0 ] && echo "OK" || echo "FAIL"
        else
            echo "Hostapd is not installed"
        fi
    else
        echo "Network interface wlan0 doesn't exist"
    fi
    ;;
    
  stop)
    ;;
    
  restart|reload)
    "$0" stop
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

