#!/bin/sh
#
# Load module....
#

case "$1" in
  start)
    printf "Load modules..."
    
    # Require for TP-Link TL-WN725N
    modprobe rfkill
    modprobe cfg80211
    modprobe r8188eu
    ;;
    
  stop)
    printf "Unload modules "
    modprobe -r r8188eu
    modprobe -r cfg80211
    modprobe -r rfkill
    ;;
    
  restart|reload)
    "$0" stop
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

