#!/bin/sh
#
# Load/Unload kernel modules...
#

case "$1" in
  start)
    echo "Load kernel modules..."
    
    # Require for TP-Link TL-WN725N
    modprobe r8188eu
    
    # Require for Netgear WNA1000Mv2
    modprobe rtl8192cu
    ;;
    
  stop)
    echo "Unload kernel modules..."
    modprobe -r r8188eu
    modprobe -r rtl8192cu
    ;;
    
  restart|reload)
    "$0" stop
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

