#!/bin/sh
#
# Start Wifi AP...
#

case "$1" in
  start)
    echo "Run Wifi AP..."
    hostapd -B /etc/hostapd.conf
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
    
  stop)
    ;;
    
  restart|reload)
    "$0" stop
    "$0" start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

